[package]
name = "abi-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
everscale-types = {git = "https://github.com/broxus/everscale-types", features = ["abi", "models"]}
abi = {path = "abi"}
nekoton-abi = { git = "https://github.com/broxus/nekoton.git" }
num-bigint = "0.4.4"